##
PyTorch-Tensors

In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

##Numpy to Tensor

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

From another tensor:

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [7]:
x_ones = torch.ones_like(x_data) #retains the properties
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=float) #overrides
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6537, 0.1992],
        [0.7344, 0.6656]], dtype=torch.float64) 



With random or constant values:

shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [8]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8574, 0.0405, 0.2097],
        [0.3993, 0.0750, 0.7219]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Use GPU if possible

In [9]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

Single-element tensors If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [ ]:


agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

In [18]:
#x = torch.zeros(5,5)
tensor = torch.rand(5,5)
tensor.add_(5)



tensor([[5.2569, 5.1036, 5.8227, 5.5676, 5.7434],
        [5.0078, 5.5981, 5.1732, 5.6107, 5.5065],
        [5.9151, 5.6784, 5.2788, 5.3293, 5.5790],
        [5.0199, 5.8131, 5.1284, 5.0372, 5.3857],
        [5.4909, 5.1151, 5.8195, 5.6017, 5.1868]])